package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"unicode/utf8"
)

// Unicode constants defined: https://gist.github.com/elsanussi-s-mneina/de4fdbf4edc9993b3b9036eb0de242cd
const HEBREW_ACCENT_ETNAHTA = "\u0591"
const HEBREW_ACCENT_SEGOL = "\u0592"
const HEBREW_ACCENT_SHALSHELET = "\u0593"
const HEBREW_ACCENT_ZAQEF_QATAN = "\u0594"
const HEBREW_ACCENT_ZAQEF_GADOL = "\u0595"
const HEBREW_ACCENT_TIPEHA = "\u0596"
const HEBREW_ACCENT_REVIA = "\u0597"
const HEBREW_ACCENT_ZARQA = "\u0598"
const HEBREW_ACCENT_PASHTA = "\u0599"
const HEBREW_ACCENT_YETIV = "\u059A"
const HEBREW_ACCENT_TEVIR = "\u059B"
const HEBREW_ACCENT_GERESH = "\u059C"
const HEBREW_ACCENT_GERESH_MUQDAM = "\u059D"
const HEBREW_ACCENT_GERSHAYIM = "\u059E"
const HEBREW_ACCENT_QARNEY_PARA = "\u059F"
const HEBREW_ACCENT_TELISHA_GEDOLA = "\u05A0"
const HEBREW_ACCENT_PAZER = "\u05A1"
const HEBREW_ACCENT_ATNAH_HAFUKH = "\u05A2"
const HEBREW_ACCENT_MUNAH = "\u05A3"
const HEBREW_ACCENT_MAHAPAKH = "\u05A4"
const HEBREW_ACCENT_MERKHA = "\u05A5"
const HEBREW_ACCENT_MERKHA_KEFULA = "\u05A6"
const HEBREW_ACCENT_DARGA = "\u05A7"
const HEBREW_ACCENT_QADMA = "\u05A8"
const HEBREW_ACCENT_TELISHA_QETANA = "\u05A9"
const HEBREW_ACCENT_YERAH_BEN_YOMO = "\u05AA"
const HEBREW_ACCENT_OLE = "\u05AB"
const HEBREW_ACCENT_ILUY = "\u05AC"
const HEBREW_ACCENT_DEHI = "\u05AD"
const HEBREW_ACCENT_ZINOR = "\u05AE"
const HEBREW_MARK_MASORA_CIRCLE = "\u05AF"
const HEBREW_POINT_SHEVA = "\u05B0"
const HEBREW_POINT_HATAF_SEGOL = "\u05B1"
const HEBREW_POINT_HATAF_PATAH = "\u05B2"
const HEBREW_POINT_HATAF_QAMATS = "\u05B3"
const HEBREW_POINT_HIRIQ = "\u05B4"
const HEBREW_POINT_TSERE = "\u05B5"
const HEBREW_POINT_SEGOL = "\u05B6"
const HEBREW_POINT_PATAH = "\u05B7"
const HEBREW_POINT_QAMATS = "\u05B8"
const HEBREW_POINT_HOLAM = "\u05B9"
const HEBREW_POINT_HOLAM_HASER_FOR_VAV = "\u05BA"
const HEBREW_POINT_QUBUTS = "\u05BB"
const HEBREW_POINT_DAGESH_OR_MAPIQ = "\u05BC"
const HEBREW_POINT_METEG = "\u05BD"
const HEBREW_PUNCTUATION_MAQAF = "\u05BE"
const HEBREW_POINT_RAFE = "\u05BF"
const HEBREW_PUNCTUATION_PASEQ = "\u05C0"
const HEBREW_POINT_SHIN_DOT = "\u05C1"
const HEBREW_POINT_SIN_DOT = "\u05C2"
const HEBREW_PUNCTUATION_SOF_PASUQ = "\u05C3"
const HEBREW_MARK_UPPER_DOT = "\u05C4"
const HEBREW_MARK_LOWER_DOT = "\u05C5"
const HEBREW_PUNCTUATION_NUN_HAFUKHA = "\u05C6"
const HEBREW_POINT_QAMATS_QATAN = "\u05C7"
const HEBREW_LETTER_ALEF = "\u05D0"
const HEBREW_LETTER_BET = "\u05D1"
const HEBREW_LETTER_GIMEL = "\u05D2"
const HEBREW_LETTER_DALET = "\u05D3"
const HEBREW_LETTER_HE = "\u05D4"
const HEBREW_LETTER_VAV = "\u05D5"
const HEBREW_LETTER_ZAYIN = "\u05D6"
const HEBREW_LETTER_HET = "\u05D7"
const HEBREW_LETTER_TET = "\u05D8"
const HEBREW_LETTER_YOD = "\u05D9"
const HEBREW_LETTER_FINAL_KAF = "\u05DA"
const HEBREW_LETTER_KAF = "\u05DB"
const HEBREW_LETTER_LAMED = "\u05DC"
const HEBREW_LETTER_FINAL_MEM = "\u05DD"
const HEBREW_LETTER_MEM = "\u05DE"
const HEBREW_LETTER_FINAL_NUN = "\u05DF"
const HEBREW_LETTER_NUN = "\u05E0"
const HEBREW_LETTER_SAMEKH = "\u05E1"
const HEBREW_LETTER_AYIN = "\u05E2"
const HEBREW_LETTER_FINAL_PE = "\u05E3"
const HEBREW_LETTER_PE = "\u05E4"
const HEBREW_LETTER_FINAL_TSADI = "\u05E5"
const HEBREW_LETTER_TSADI = "\u05E6"
const HEBREW_LETTER_QOF = "\u05E7"
const HEBREW_LETTER_RESH = "\u05E8"
const HEBREW_LETTER_SHIN = "\u05E9"
const HEBREW_LETTER_TAV = "\u05EA"
const HEBREW_YOD_TRIANGLE = "\u05EF"
const HEBREW_LIGATURE_YIDDISH_DOUBLE_VAV = "\u05F0"
const HEBREW_LIGATURE_YIDDISH_VAV_YOD = "\u05F1"
const HEBREW_LIGATURE_YIDDISH_DOUBLE_YOD = "\u05F2"
const HEBREW_PUNCTUATION_GERESH = "\u05F3"
const HEBREW_PUNCTUATION_GERSHAYIM = "\u05F4"
const ARABIC_NUMBER_SIGN = "\u0600"
const ARABIC_SIGN_SANAH = "\u0601"
const ARABIC_FOOTNOTE_MARKER = "\u0602"
const ARABIC_SIGN_SAFHA = "\u0603"
const ARABIC_SIGN_SAMVAT = "\u0604"
const ARABIC_NUMBER_MARK_ABOVE = "\u0605"
const ARABIC_INDIC_CUBE_ROOT = "\u0606"
const ARABIC_INDIC_FOURTH_ROOT = "\u0607"
const ARABIC_RAY = "\u0608"
const ARABIC_INDIC_PER_MILLE_SIGN = "\u0609"
const ARABIC_INDIC_PER_TEN_THOUSAND_SIGN = "\u060A"
const AFGHANI_SIGN = "\u060B"
const ARABIC_COMMA = "\u060C"
const ARABIC_DATE_SEPARATOR = "\u060D"
const ARABIC_POETIC_VERSE_SIGN = "\u060E"
const ARABIC_SIGN_MISRA = "\u060F"
const ARABIC_SIGN_SALLALLAHOU_ALAYHE_WASSALLAM = "\u0610"
const ARABIC_SIGN_ALAYHE_ASSALLAM = "\u0611"
const ARABIC_SIGN_RAHMATULLAH_ALAYHE = "\u0612"
const ARABIC_SIGN_RADI_ALLAHOU_ANHU = "\u0613"
const ARABIC_SIGN_TAKHALLUS = "\u0614"
const ARABIC_SMALL_HIGH_TAH = "\u0615"
const ARABIC_SMALL_HIGH_LIGATURE_ALEF_WITH_LAM_WITH_YEH = "\u0616"
const ARABIC_SMALL_HIGH_ZAIN = "\u0617"
const ARABIC_SMALL_FATHA = "\u0618"
const ARABIC_SMALL_DAMMA = "\u0619"
const ARABIC_SMALL_KASRA = "\u061A"
const ARABIC_SEMICOLON = "\u061B"
const ARABIC_LETTER_MARK = "\u061C"
const ARABIC_END_OF_TEXT_MARK = "\u061D"
const ARABIC_TRIPLE_DOT_PUNCTUATION_MARK = "\u061E"
const ARABIC_QUESTION_MARK = "\u061F"
const ARABIC_LETTER_KASHMIRI_YEH = "\u0620"
const ARABIC_LETTER_HAMZA = "\u0621"
const ARABIC_LETTER_ALEF_WITH_MADDA_ABOVE = "\u0622"
const ARABIC_LETTER_ALEF_WITH_HAMZA_ABOVE = "\u0623"
const ARABIC_LETTER_WAW_WITH_HAMZA_ABOVE = "\u0624"
const ARABIC_LETTER_ALEF_WITH_HAMZA_BELOW = "\u0625"
const ARABIC_LETTER_YEH_WITH_HAMZA_ABOVE = "\u0626"
const ARABIC_LETTER_ALEF = "\u0627"
const ARABIC_LETTER_BEH = "\u0628"
const ARABIC_LETTER_TEH_MARBUTA = "\u0629"
const ARABIC_LETTER_TEH = "\u062A"
const ARABIC_LETTER_THEH = "\u062B"
const ARABIC_LETTER_JEEM = "\u062C"
const ARABIC_LETTER_HAH = "\u062D"
const ARABIC_LETTER_KHAH = "\u062E"
const ARABIC_LETTER_DAL = "\u062F"
const ARABIC_LETTER_THAL = "\u0630"
const ARABIC_LETTER_REH = "\u0631"
const ARABIC_LETTER_ZAIN = "\u0632"
const ARABIC_LETTER_SEEN = "\u0633"
const ARABIC_LETTER_SHEEN = "\u0634"
const ARABIC_LETTER_SAD = "\u0635"
const ARABIC_LETTER_DAD = "\u0636"
const ARABIC_LETTER_TAH = "\u0637"
const ARABIC_LETTER_ZAH = "\u0638"
const ARABIC_LETTER_AIN = "\u0639"
const ARABIC_LETTER_GHAIN = "\u063A"
const ARABIC_LETTER_KEHEH_WITH_TWO_DOTS_ABOVE = "\u063B"
const ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_BELOW = "\u063C"
const ARABIC_LETTER_FARSI_YEH_WITH_INVERTED_V = "\u063D"
const ARABIC_LETTER_FARSI_YEH_WITH_TWO_DOTS_ABOVE = "\u063E"
const ARABIC_LETTER_FARSI_YEH_WITH_THREE_DOTS_ABOVE = "\u063F"
const ARABIC_TATWEEL = "\u0640"
const ARABIC_LETTER_FEH = "\u0641"
const ARABIC_LETTER_QAF = "\u0642"
const ARABIC_LETTER_KAF = "\u0643"
const ARABIC_LETTER_LAM = "\u0644"
const ARABIC_LETTER_MEEM = "\u0645"
const ARABIC_LETTER_NOON = "\u0646"
const ARABIC_LETTER_HEH = "\u0647"
const ARABIC_LETTER_WAW = "\u0648"
const ARABIC_LETTER_ALEF_MAKSURA = "\u0649"
const ARABIC_LETTER_YEH = "\u064A"
const ARABIC_FATHATAN = "\u064B"
const ARABIC_DAMMATAN = "\u064C"
const ARABIC_KASRATAN = "\u064D"
const ARABIC_FATHA = "\u064E"
const ARABIC_DAMMA = "\u064F"
const ARABIC_KASRA = "\u0650"
const ARABIC_SHADDA = "\u0651"
const ARABIC_SUKUN = "\u0652"
const ARABIC_MADDAH_ABOVE = "\u0653"
const ARABIC_HAMZA_ABOVE = "\u0654"
const ARABIC_HAMZA_BELOW = "\u0655"
const ARABIC_SUBSCRIPT_ALEF = "\u0656"
const ARABIC_INVERTED_DAMMA = "\u0657"
const ARABIC_MARK_NOON_GHUNNA = "\u0658"
const ARABIC_ZWARAKAY = "\u0659"
const ARABIC_VOWEL_SIGN_SMALL_V_ABOVE = "\u065A"
const ARABIC_VOWEL_SIGN_INVERTED_SMALL_V_ABOVE = "\u065B"
const ARABIC_VOWEL_SIGN_DOT_BELOW = "\u065C"
const ARABIC_REVERSED_DAMMA = "\u065D"
const ARABIC_FATHA_WITH_TWO_DOTS = "\u065E"
const ARABIC_WAVY_HAMZA_BELOW = "\u065F"
const ARABIC_INDIC_DIGIT_ZERO = "\u0660"
const ARABIC_INDIC_DIGIT_ONE = "\u0661"
const ARABIC_INDIC_DIGIT_TWO = "\u0662"
const ARABIC_INDIC_DIGIT_THREE = "\u0663"
const ARABIC_INDIC_DIGIT_FOUR = "\u0664"
const ARABIC_INDIC_DIGIT_FIVE = "\u0665"
const ARABIC_INDIC_DIGIT_SIX = "\u0666"
const ARABIC_INDIC_DIGIT_SEVEN = "\u0667"
const ARABIC_INDIC_DIGIT_EIGHT = "\u0668"
const ARABIC_INDIC_DIGIT_NINE = "\u0669"
const ARABIC_PERCENT_SIGN = "\u066A"
const ARABIC_DECIMAL_SEPARATOR = "\u066B"
const ARABIC_THOUSANDS_SEPARATOR = "\u066C"
const ARABIC_FIVE_POINTED_STAR = "\u066D"
const ARABIC_LETTER_DOTLESS_BEH = "\u066E"
const ARABIC_LETTER_DOTLESS_QAF = "\u066F"
const ARABIC_LETTER_SUPERSCRIPT_ALEF = "\u0670"
const ARABIC_LETTER_ALEF_WASLA = "\u0671"
const ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_ABOVE = "\u0672"
const ARABIC_LETTER_ALEF_WITH_WAVY_HAMZA_BELOW = "\u0673"
const ARABIC_LETTER_HIGH_HAMZA = "\u0674"
const ARABIC_LETTER_HIGH_HAMZA_ALEF = "\u0675"
const ARABIC_LETTER_HIGH_HAMZA_WAW = "\u0676"
const ARABIC_LETTER_U_WITH_HAMZA_ABOVE = "\u0677"
const ARABIC_LETTER_HIGH_HAMZA_YEH = "\u0678"
const ARABIC_LETTER_TTEH = "\u0679"
const ARABIC_LETTER_TTEHEH = "\u067A"
const ARABIC_LETTER_BEEH = "\u067B"
const ARABIC_LETTER_TEH_WITH_RING = "\u067C"
const ARABIC_LETTER_TEH_WITH_THREE_DOTS_ABOVE_DOWNWARDS = "\u067D"
const ARABIC_LETTER_PEH = "\u067E"
const ARABIC_LETTER_TEHEH = "\u067F"
const ARABIC_LETTER_BEHEH = "\u0680"
const ARABIC_LETTER_HAH_WITH_HAMZA_ABOVE = "\u0681"
const ARABIC_LETTER_HAH_WITH_TWO_DOTS_VERTICAL_ABOVE = "\u0682"
const ARABIC_LETTER_NYEH = "\u0683"
const ARABIC_LETTER_DYEH = "\u0684"
const ARABIC_LETTER_HAH_WITH_THREE_DOTS_ABOVE = "\u0685"
const ARABIC_LETTER_TCHEH = "\u0686"
const ARABIC_LETTER_TCHEHEH = "\u0687"
const ARABIC_LETTER_DDAL = "\u0688"
const ARABIC_LETTER_DAL_WITH_RING = "\u0689"
const ARABIC_LETTER_DAL_WITH_DOT_BELOW = "\u068A"
const ARABIC_LETTER_DAL_WITH_DOT_BELOW_AND_SMALL_TAH = "\u068B"
const ARABIC_LETTER_DAHAL = "\u068C"
const ARABIC_LETTER_DDAHAL = "\u068D"
const ARABIC_LETTER_DUL = "\u068E"
const ARABIC_LETTER_DAL_WITH_THREE_DOTS_ABOVE_DOWNWARDS = "\u068F"
const ARABIC_LETTER_DAL_WITH_FOUR_DOTS_ABOVE = "\u0690"
const ARABIC_LETTER_RREH = "\u0691"
const ARABIC_LETTER_REH_WITH_SMALL_V = "\u0692"
const ARABIC_LETTER_REH_WITH_RING = "\u0693"
const ARABIC_LETTER_REH_WITH_DOT_BELOW = "\u0694"
const ARABIC_LETTER_REH_WITH_SMALL_V_BELOW = "\u0695"
const ARABIC_LETTER_REH_WITH_DOT_BELOW_AND_DOT_ABOVE = "\u0696"
const ARABIC_LETTER_REH_WITH_TWO_DOTS_ABOVE = "\u0697"
const ARABIC_LETTER_JEH = "\u0698"
const ARABIC_LETTER_REH_WITH_FOUR_DOTS_ABOVE = "\u0699"
const ARABIC_LETTER_SEEN_WITH_DOT_BELOW_AND_DOT_ABOVE = "\u069A"
const ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW = "\u069B"
const ARABIC_LETTER_SEEN_WITH_THREE_DOTS_BELOW_AND_THREE_DOTS_ABOVE = "\u069C"
const ARABIC_LETTER_SAD_WITH_TWO_DOTS_BELOW = "\u069D"
const ARABIC_LETTER_SAD_WITH_THREE_DOTS_ABOVE = "\u069E"
const ARABIC_LETTER_TAH_WITH_THREE_DOTS_ABOVE = "\u069F"
const ARABIC_LETTER_AIN_WITH_THREE_DOTS_ABOVE = "\u06A0"
const ARABIC_LETTER_DOTLESS_FEH = "\u06A1"
const ARABIC_LETTER_FEH_WITH_DOT_MOVED_BELOW = "\u06A2"
const ARABIC_LETTER_FEH_WITH_DOT_BELOW = "\u06A3"
const ARABIC_LETTER_VEH = "\u06A4"
const ARABIC_LETTER_FEH_WITH_THREE_DOTS_BELOW = "\u06A5"
const ARABIC_LETTER_PEHEH = "\u06A6"
const ARABIC_LETTER_QAF_WITH_DOT_ABOVE = "\u06A7"
const ARABIC_LETTER_QAF_WITH_THREE_DOTS_ABOVE = "\u06A8"
const ARABIC_LETTER_KEHEH = "\u06A9"
const ARABIC_LETTER_SWASH_KAF = "\u06AA"
const ARABIC_LETTER_KAF_WITH_RING = "\u06AB"
const ARABIC_LETTER_KAF_WITH_DOT_ABOVE = "\u06AC"
const ARABIC_LETTER_NG = "\u06AD"
const ARABIC_LETTER_KAF_WITH_THREE_DOTS_BELOW = "\u06AE"
const ARABIC_LETTER_GAF = "\u06AF"
const ARABIC_LETTER_GAF_WITH_RING = "\u06B0"
const ARABIC_LETTER_NGOEH = "\u06B1"
const ARABIC_LETTER_GAF_WITH_TWO_DOTS_BELOW = "\u06B2"
const ARABIC_LETTER_GUEH = "\u06B3"
const ARABIC_LETTER_GAF_WITH_THREE_DOTS_ABOVE = "\u06B4"
const ARABIC_LETTER_LAM_WITH_SMALL_V = "\u06B5"
const ARABIC_LETTER_LAM_WITH_DOT_ABOVE = "\u06B6"
const ARABIC_LETTER_LAM_WITH_THREE_DOTS_ABOVE = "\u06B7"
const ARABIC_LETTER_LAM_WITH_THREE_DOTS_BELOW = "\u06B8"
const ARABIC_LETTER_NOON_WITH_DOT_BELOW = "\u06B9"
const ARABIC_LETTER_NOON_GHUNNA = "\u06BA"
const ARABIC_LETTER_RNOON = "\u06BB"
const ARABIC_LETTER_NOON_WITH_RING = "\u06BC"
const ARABIC_LETTER_NOON_WITH_THREE_DOTS_ABOVE = "\u06BD"
const ARABIC_LETTER_HEH_DOACHASHMEE = "\u06BE"
const ARABIC_LETTER_TCHEH_WITH_DOT_ABOVE = "\u06BF"
const ARABIC_LETTER_HEH_WITH_YEH_ABOVE = "\u06C0"
const ARABIC_LETTER_HEH_GOAL = "\u06C1"
const ARABIC_LETTER_HEH_GOAL_WITH_HAMZA_ABOVE = "\u06C2"
const ARABIC_LETTER_TEH_MARBUTA_GOAL = "\u06C3"
const ARABIC_LETTER_WAW_WITH_RING = "\u06C4"
const ARABIC_LETTER_KIRGHIZ_OE = "\u06C5"
const ARABIC_LETTER_OE = "\u06C6"
const ARABIC_LETTER_U = "\u06C7"
const ARABIC_LETTER_YU = "\u06C8"
const ARABIC_LETTER_KIRGHIZ_YU = "\u06C9"
const ARABIC_LETTER_WAW_WITH_TWO_DOTS_ABOVE = "\u06CA"
const ARABIC_LETTER_VE = "\u06CB"
const ARABIC_LETTER_FARSI_YEH = "\u06CC"
const ARABIC_LETTER_YEH_WITH_TAIL = "\u06CD"
const ARABIC_LETTER_YEH_WITH_SMALL_V = "\u06CE"
const ARABIC_LETTER_WAW_WITH_DOT_ABOVE = "\u06CF"
const ARABIC_LETTER_E = "\u06D0"
const ARABIC_LETTER_YEH_WITH_THREE_DOTS_BELOW = "\u06D1"
const ARABIC_LETTER_YEH_BARREE = "\u06D2"
const ARABIC_LETTER_YEH_BARREE_WITH_HAMZA_ABOVE = "\u06D3"
const ARABIC_FULL_STOP = "\u06D4"
const ARABIC_LETTER_AE = "\u06D5"
const ARABIC_SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA = "\u06D6"
const ARABIC_SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA = "\u06D7"
const ARABIC_SMALL_HIGH_MEEM_INITIAL_FORM = "\u06D8"
const ARABIC_SMALL_HIGH_LAM_ALEF = "\u06D9"
const ARABIC_SMALL_HIGH_JEEM = "\u06DA"
const ARABIC_SMALL_HIGH_THREE_DOTS = "\u06DB"
const ARABIC_SMALL_HIGH_SEEN = "\u06DC"
const ARABIC_END_OF_AYAH = "\u06DD"
const ARABIC_START_OF_RUB_EL_HIZB = "\u06DE"
const ARABIC_SMALL_HIGH_ROUNDED_ZERO = "\u06DF"
const ARABIC_SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO = "\u06E0"
const ARABIC_SMALL_HIGH_DOTLESS_HEAD_OF_KHAH = "\u06E1"
const ARABIC_SMALL_HIGH_MEEM_ISOLATED_FORM = "\u06E2"
const ARABIC_SMALL_LOW_SEEN = "\u06E3"
const ARABIC_SMALL_HIGH_MADDA = "\u06E4"
const ARABIC_SMALL_WAW = "\u06E5"
const ARABIC_SMALL_YEH = "\u06E6"
const ARABIC_SMALL_HIGH_YEH = "\u06E7"
const ARABIC_SMALL_HIGH_NOON = "\u06E8"
const ARABIC_PLACE_OF_SAJDAH = "\u06E9"
const ARABIC_EMPTY_CENTRE_LOW_STOP = "\u06EA"
const ARABIC_EMPTY_CENTRE_HIGH_STOP = "\u06EB"
const ARABIC_ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE = "\u06EC"
const ARABIC_SMALL_LOW_MEEM = "\u06ED"
const ARABIC_LETTER_DAL_WITH_INVERTED_V = "\u06EE"
const ARABIC_LETTER_REH_WITH_INVERTED_V = "\u06EF"
const EXTENDED_ARABIC_INDIC_DIGIT_ZERO = "\u06F0"
const EXTENDED_ARABIC_INDIC_DIGIT_ONE = "\u06F1"
const EXTENDED_ARABIC_INDIC_DIGIT_TWO = "\u06F2"
const EXTENDED_ARABIC_INDIC_DIGIT_THREE = "\u06F3"
const EXTENDED_ARABIC_INDIC_DIGIT_FOUR = "\u06F4"
const EXTENDED_ARABIC_INDIC_DIGIT_FIVE = "\u06F5"
const EXTENDED_ARABIC_INDIC_DIGIT_SIX = "\u06F6"
const EXTENDED_ARABIC_INDIC_DIGIT_SEVEN = "\u06F7"
const EXTENDED_ARABIC_INDIC_DIGIT_EIGHT = "\u06F8"
const EXTENDED_ARABIC_INDIC_DIGIT_NINE = "\u06F9"
const ARABIC_LETTER_SHEEN_WITH_DOT_BELOW = "\u06FA"
const ARABIC_LETTER_DAD_WITH_DOT_BELOW = "\u06FB"
const ARABIC_LETTER_GHAIN_WITH_DOT_BELOW = "\u06FC"
const ARABIC_SIGN_SINDHI_AMPERSAND = "\u06FD"
const ARABIC_SIGN_SINDHI_POSTPOSITION_MEN = "\u06FE"
const ARABIC_LETTER_HEH_WITH_INVERTED_V = "\u06FF"

var transliterationTable = map[string]string{HEBREW_LETTER_ALEF: ARABIC_LETTER_ALEF,
	HEBREW_LETTER_BET:         ARABIC_LETTER_BEH,
	HEBREW_LETTER_GIMEL:       ARABIC_LETTER_JEEM,
	HEBREW_LETTER_DALET:       ARABIC_LETTER_DAL,
	HEBREW_LETTER_HE:          ARABIC_LETTER_HEH,
	HEBREW_LETTER_VAV:         ARABIC_LETTER_WAW,
	HEBREW_LETTER_ZAYIN:       ARABIC_LETTER_ZAIN,
	HEBREW_LETTER_HET:         ARABIC_LETTER_HAH,
	HEBREW_LETTER_TET:         ARABIC_LETTER_TAH,
	HEBREW_LETTER_YOD:         ARABIC_LETTER_YEH,
	HEBREW_LETTER_FINAL_KAF:   ARABIC_LETTER_KAF,
	HEBREW_LETTER_KAF:         ARABIC_LETTER_KAF,
	HEBREW_LETTER_LAMED:       ARABIC_LETTER_LAM,
	HEBREW_LETTER_FINAL_MEM:   ARABIC_LETTER_MEEM,
	HEBREW_LETTER_MEM:         ARABIC_LETTER_MEEM,
	HEBREW_LETTER_FINAL_NUN:   ARABIC_LETTER_NOON,
	HEBREW_LETTER_NUN:         ARABIC_LETTER_NOON,
	HEBREW_LETTER_SAMEKH:      ARABIC_LETTER_SEEN,
	HEBREW_LETTER_AYIN:        ARABIC_LETTER_AIN,
	HEBREW_LETTER_FINAL_PE:    ARABIC_LETTER_FEH,
	HEBREW_LETTER_PE:          ARABIC_LETTER_FEH,
	HEBREW_LETTER_FINAL_TSADI: ARABIC_LETTER_SAD,
	HEBREW_LETTER_TSADI:       ARABIC_LETTER_SAD,
	HEBREW_LETTER_QOF:         ARABIC_LETTER_QAF,
	HEBREW_LETTER_RESH:        ARABIC_LETTER_REH,
	HEBREW_LETTER_SHIN:        ARABIC_LETTER_SHEEN,
	HEBREW_LETTER_TAV:         ARABIC_LETTER_TEH,
	",":                       ARABIC_COMMA,
	"?":                       ARABIC_QUESTION_MARK}

func trimLeftOneRune(text string) string {
	_, numberOfBytesInFirstRune := utf8.DecodeRuneInString(text)
	return text[numberOfBytesInFirstRune:]
}

func main() {
	// Convert Hebrew letters to Arabic letters.
	// The first letter of Hebrew alphabet is HEBREW LETTER ALEF
	// and its Unicode code point is U+05D0.

	// This corresponds to the ARABIC LETTER ALEF, which
	// has Unicode code point U+0627.
	var hebrewText string

	// Read all text from standard In
	scanner := bufio.NewScanner(os.Stdin)
	scanner.Scan()
	hebrewText = scanner.Text()

	fmt.Println(transliterate(hebrewText))
}

func transliterate(hebrewText string) string {
	var arabicText string

	// while there is still text to gobble up
	for len(hebrewText) > 0 {

		var foundMatch bool

		foundMatch = false
		for hebrewCell, arabicCell := range transliterationTable {
			if len(hebrewCell) > 0 && strings.HasPrefix(hebrewText, hebrewCell) {
				foundMatch = true
				arabicText += arabicCell

				// Make remaining hebrew text smaller by getting rid of some text at the beginning
				hebrewText = strings.TrimPrefix(hebrewText, hebrewCell)
			}
		}

		// If no match was found, at least delete the first character:
		if !foundMatch {
			// Any unrecognized character should
			// be transliterated as itself (i.e. not transliterated at all, but
			// copied into the result).
			hebrewTextAsRunes := []rune(hebrewText)
			firstCharacterString := string(hebrewTextAsRunes[0])
			arabicText += firstCharacterString

			hebrewText = trimLeftOneRune(hebrewText)
		}

	}

	return arabicText
}
